services:
  # vernemq:
  #     image: vernemq/vernemq:latest
  #     container_name: vernemq
  #     ports:
  #       - "1883:1883"
  #       - "8888:8888"  # Dashboard HTTP
  #     environment:
  #       - DOCKER_VERNEMQ_ACCEPT_EULA=yes
  #       - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
  #       - DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=3,4,5

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2
    container_name: fluentbit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    ports:
      - "1883:1883"  # MQTT
      - "2020:2020"  # optional: HTTP API para debug

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken

  # telegraf:
  #   image: telegraf:1.30
  #   container_name: telegraf
  #   restart: unless-stopped
  #   depends_on:
  #     - influxdb
  #     - emqx
  #   volumes:
  #     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  # grafana:
  #   image: grafana/grafana-oss:10.2.3
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - influxdb
  #   volumes:
  #     - grafana_data:/var/lib/grafana

  # streamlit:
  #   build: ./streamlit
  #   container_name: streamlit
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - influxdb

volumes:
  influxdb_data:
  grafana_data: